//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 04:21:21 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://rca.ac.rw/anselme/soap-app", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.rca_ac_rw.anselme.soap_app;
